Dominik/audio
zsacul/TowerDefenseVR2020 pull request #18
Opened 2020-03-25 03:13 UTC by StDanger

2020-03-26 22:56 UTC, KrzysiekSlawik requested changes
przyczepiłem się do kilku pierdoł, taka praca. Dodatkowo nazwy metod z WielkiejLitery

2020-03-26 22:56 UTC, KrzysiekSlawik commented on Assets/TowerDefense/Scripts/Audio/AudioManager.cs
> +    public static AudioManager I;
ze względu na konwencję lepiej używać nazwy Instance, bo od razu wiadomo, że chodzi o singleton

2020-03-26 22:56 UTC, KrzysiekSlawik commented on Assets/TowerDefense/Scripts/Audio/AudioManager.cs
> +    private IEnumerator fadeOutCoorutine(AudioSource source, float duration, AnimationCurve curve, float startingVol)
literówka w nazwie

2020-03-26 22:56 UTC, KrzysiekSlawik commented on Assets/TowerDefense/Scripts/Audio/AudioManager.cs
> +    private IEnumerator fadeInCoorutine(AudioSource source, float duration, AnimationCurve curve, float targetVol)
literówka w nazwie

2020-03-27 15:48 UTC, StDanger commented
Poprawione, nie byłem świadomy że to wszystko będzie tak pilnowane :d

2020-03-30 17:53 UTC, KrzysiekSlawik approved these changes

2020-03-30 17:53 UTC, merged